import type { User, Branch, Course, Enrollment, Attendance, Payment, Revenue, Schedule } from "./database.types"

export const jsonDatabase = {
  users: [
    // Super Admin
    {
      id: "1",
      phone: "0845678901",
      first_name: "สุพัตรา",
      last_name: "ผู้จัดการใหญ่",
      nickname: "ปุ๊",
      email: "superadmin@thaitutoring.com",
      role: "superadmin" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    // Branch Admins
    {
      id: "2",
      phone: "0812345678",
      first_name: "สมชาย",
      last_name: "ผู้จัดการ",
      nickname: "ชาย",
      email: "admin.bangkok@thaitutoring.com",
      role: "admin" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "3",
      phone: "0853456789",
      first_name: "สมหญิง",
      last_name: "ผู้จัดการ",
      nickname: "หญิง",
      email: "admin.chiangmai@thaitutoring.com",
      role: "admin" as const,
      branch_id: "2",
      branch_name: "สาขาเชียงใหม่",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "4",
      phone: "0864567890",
      first_name: "สมศักดิ์",
      last_name: "ผู้จัดการ",
      nickname: "ศักดิ์",
      email: "admin.khonkaen@thaitutoring.com",
      role: "admin" as const,
      branch_id: "3",
      branch_name: "สาขาขอนแก่น",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    // Teachers
    {
      id: "5",
      phone: "0834567890",
      first_name: "อาจารย์สมใจ",
      last_name: "คณิตศาสตร์",
      nickname: "ครูใจ",
      email: "teacher1@thaitutoring.com",
      role: "teacher" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "6",
      phone: "0875678901",
      first_name: "อาจารย์สมหวัง",
      last_name: "ภาษาอังกฤษ",
      nickname: "ครูหวัง",
      email: "teacher2@thaitutoring.com",
      role: "teacher" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "7",
      phone: "0886789012",
      first_name: "อาจารย์สมศรี",
      last_name: "วิทยาศาสตร์",
      nickname: "ครูศรี",
      email: "teacher3@thaitutoring.com",
      role: "teacher" as const,
      branch_id: "2",
      branch_name: "สาขาเชียงใหม่",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "8",
      phone: "0897890123",
      first_name: "อาจารย์สมพงษ์",
      last_name: "ฟิสิกส์",
      nickname: "ครูพงษ์",
      email: "teacher4@thaitutoring.com",
      role: "teacher" as const,
      branch_id: "3",
      branch_name: "สาขาขอนแก่น",
      current_grade: null,
      guardian_name: null,
      guardian_surname: null,
      guardian_occupation: null,
      guardian_line_id: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    // Students
    {
      id: "9",
      phone: "0823456789",
      first_name: "สมชาติ",
      last_name: "นักเรียนดี",
      nickname: "ชาติ",
      email: "student1@email.com",
      role: "student" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: "ม.3",
      guardian_name: "นายสมศักดิ์",
      guardian_surname: "นักเรียนดี",
      guardian_occupation: "ข้าราชการ",
      guardian_line_id: "guardian001",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "10",
      phone: "0856789012",
      first_name: "สมหญิง",
      last_name: "เรียนเก่ง",
      nickname: "หญิง",
      email: "student2@email.com",
      role: "student" as const,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      current_grade: "ม.2",
      guardian_name: "นางสมใจ",
      guardian_surname: "เรียนเก่ง",
      guardian_occupation: "พนักงานบริษัท",
      guardian_line_id: "guardian002",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "11",
      phone: "0867890123",
      first_name: "สมศักดิ์",
      last_name: "ขยันเรียน",
      nickname: "ศักดิ์",
      email: "student3@email.com",
      role: "student" as const,
      branch_id: "2",
      branch_name: "สาขาเชียงใหม่",
      current_grade: "ม.1",
      guardian_name: "นายสมชาย",
      guardian_surname: "ขยันเรียน",
      guardian_occupation: "ธุรกิจส่วนตัว",
      guardian_line_id: "guardian003",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "12",
      phone: "0878901234",
      first_name: "สมปอง",
      last_name: "มานะเรียน",
      nickname: "ปอง",
      email: "student4@email.com",
      role: "student" as const,
      branch_id: "3",
      branch_name: "สาขาขอนแก่น",
      current_grade: "ม.6",
      guardian_name: "นางสมศรี",
      guardian_surname: "มานะเรียน",
      guardian_occupation: "ครู",
      guardian_line_id: "guardian004",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ] as User[],

  branches: [
    {
      id: "1",
      name: "สาขากรุงเทพ",
      address: "123 ถนนสุขุมวิท แขวงคลองตัน เขตคลองตัน กรุงเทพฯ 10110",
      phone: "02-123-4567",
      manager_name: "สมชาย ผู้จัดการ",
      commission_rate: 0.15,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "2",
      name: "สาขาเชียงใหม่",
      address: "456 ถนนนิมมานเหมินท์ ตำบลสุเทพ อำเภอเมือง เชียงใหม่ 50200",
      phone: "053-123-456",
      manager_name: "สมหญิง ผู้จัดการ",
      commission_rate: 0.12,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "3",
      name: "สาขาขอนแก่น",
      address: "789 ถนนศรีจันทร์ ตำบลในเมือง อำเภอเมือง ขอนแก่น 40000",
      phone: "043-123-789",
      manager_name: "สมศักดิ์ ผู้จัดการ",
      commission_rate: 0.1,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "4",
      name: "สาขาภูเก็ต",
      address: "321 ถนนราษฎร์อุทิศ ตำบลป่าตอง อำเภอกะทู้ ภูเก็ต 83150",
      phone: "076-123-321",
      manager_name: "สมพงษ์ ผู้จัดการ",
      commission_rate: 0.13,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "5",
      name: "สาขาหาดใหญ่",
      address: "654 ถนนเพชรเกษม ตำบลหาดใหญ่ อำเภอหาดใหญ่ สงขลา 90110",
      phone: "074-123-654",
      manager_name: "สมใจ ผู้จัดการ",
      commission_rate: 0.11,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ] as Branch[],

  courses: [
    {
      id: "1",
      name: "คณิตศาสตร์ ม.3",
      description: "คณิตศาสตร์พื้นฐานสำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 3",
      grade_level: "ม.3",
      total_sessions: 20,
      price: 3000,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      teacher_id: "5",
      teacher_name: "อาจารย์สมใจ คณิตศาสตร์",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "2",
      name: "ภาษาอังกฤษ ม.2",
      description: "ภาษาอังกฤษพื้นฐานสำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 2",
      grade_level: "ม.2",
      total_sessions: 16,
      price: 2800,
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      teacher_id: "6",
      teacher_name: "อาจารย์สมหวัง ภาษาอังกฤษ",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "3",
      name: "วิทยาศาสตร์ ม.1",
      description: "วิทยาศาสตร์พื้นฐานสำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 1",
      grade_level: "ม.1",
      total_sessions: 18,
      price: 2500,
      branch_id: "2",
      branch_name: "สาขาเชียงใหม่",
      teacher_id: "7",
      teacher_name: "อาจารย์สมศรี วิทยาศาสตร์",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "4",
      name: "ฟิสิกส์ ม.6",
      description: "ฟิสิกส์ขั้นสูงสำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 6",
      grade_level: "ม.6",
      total_sessions: 24,
      price: 4000,
      branch_id: "3",
      branch_name: "สาขาขอนแก่น",
      teacher_id: "8",
      teacher_name: "อาจารย์สมพงษ์ ฟิสิกส์",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ] as Course[],

  enrollments: [
    {
      id: "1",
      student_id: "9",
      student_first_name: "สมชาติ",
      student_last_name: "นักเรียนดี",
      course_id: "1",
      course_name: "คณิตศาสตร์ ม.3",
      enrollment_date: "2024-01-15",
      payment_status: "paid" as const,
      status: "active" as const,
      sessions_attended: 8,
      created_at: "2024-01-15T00:00:00Z",
      updated_at: "2024-01-15T00:00:00Z",
    },
    {
      id: "2",
      student_id: "10",
      student_first_name: "สมหญิง",
      student_last_name: "เรียนเก่ง",
      course_id: "2",
      course_name: "ภาษาอังกฤษ ม.2",
      enrollment_date: "2024-01-20",
      payment_status: "pending" as const,
      status: "active" as const,
      sessions_attended: 5,
      created_at: "2024-01-20T00:00:00Z",
      updated_at: "2024-01-20T00:00:00Z",
    },
    {
      id: "3",
      student_id: "11",
      student_first_name: "สมศักดิ์",
      student_last_name: "ขยันเรียน",
      course_id: "3",
      course_name: "วิทยาศาสตร์ ม.1",
      enrollment_date: "2024-01-25",
      payment_status: "paid" as const,
      status: "active" as const,
      sessions_attended: 12,
      created_at: "2024-01-25T00:00:00Z",
      updated_at: "2024-01-25T00:00:00Z",
    },
    {
      id: "4",
      student_id: "12",
      student_first_name: "สมปอง",
      student_last_name: "มานะเรียน",
      course_id: "4",
      course_name: "ฟิสิกส์ ม.6",
      enrollment_date: "2024-02-01",
      payment_status: "refunded" as const,
      status: "cancelled" as const,
      sessions_attended: 3,
      created_at: "2024-02-01T00:00:00Z",
      updated_at: "2024-02-01T00:00:00Z",
    },
  ] as Enrollment[],

  attendance: [
    {
      id: "1",
      student_id: "9",
      course_id: "1",
      class_date: "2024-01-16",
      status: "present" as const,
      check_in_time: "09:00:00",
      created_at: "2024-01-16T09:00:00Z",
      updated_at: "2024-01-16T09:00:00Z",
    },
    {
      id: "2",
      student_id: "10",
      course_id: "2",
      class_date: "2024-01-21",
      status: "late" as const,
      check_in_time: "09:15:00",
      notes: "มาสาย 15 นาที",
      created_at: "2024-01-21T09:15:00Z",
      updated_at: "2024-01-21T09:15:00Z",
    },
  ] as Attendance[],

  payments: [
    {
      id: "1",
      enrollment_id: "1",
      amount: 3000,
      payment_date: "2024-01-15",
      payment_method: "transfer" as const,
      status: "completed" as const,
      created_at: "2024-01-15T00:00:00Z",
      updated_at: "2024-01-15T00:00:00Z",
    },
    {
      id: "2",
      enrollment_id: "3",
      amount: 2500,
      payment_date: "2024-01-25",
      payment_method: "cash" as const,
      status: "completed" as const,
      created_at: "2024-01-25T00:00:00Z",
      updated_at: "2024-01-25T00:00:00Z",
    },
  ] as Payment[],

  revenue: [
    {
      id: "1",
      branch_id: "1",
      branch_name: "สาขากรุงเทพ",
      course_id: "1",
      student_id: "9",
      amount: 3000,
      commission: 450,
      date: "2024-01-15",
      source: "course_enrollment",
      description: "ลงทะเบียนคอร์ส คณิตศาสตร์ ม.3",
      created_at: "2024-01-15T00:00:00Z",
      updated_at: "2024-01-15T00:00:00Z",
    },
    {
      id: "2",
      branch_id: "2",
      branch_name: "สาขาเชียงใหม่",
      course_id: "3",
      student_id: "11",
      amount: 2500,
      commission: 300,
      date: "2024-01-25",
      source: "course_enrollment",
      description: "ลงทะเบียนคอร์ส วิทยาศาสตร์ ม.1",
      created_at: "2024-01-25T00:00:00Z",
      updated_at: "2024-01-25T00:00:00Z",
    },
  ] as Revenue[],

  schedules: [
    {
      id: "1",
      course_id: "1",
      day_of_week: 1, // Monday
      start_time: "09:00",
      end_time: "10:30",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "2",
      course_id: "1",
      day_of_week: 3, // Wednesday
      start_time: "09:00",
      end_time: "10:30",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "3",
      course_id: "2",
      day_of_week: 2, // Tuesday
      start_time: "14:00",
      end_time: "15:30",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: "4",
      course_id: "2",
      day_of_week: 4, // Thursday
      start_time: "14:00",
      end_time: "15:30",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ] as Schedule[],

  // Helper methods for branch revenue analysis
  getBranchRevenueAnalysis: async (branchId?: string) => {
    const branches = branchId ? jsonDatabase.branches.filter((b) => b.id === branchId) : jsonDatabase.branches
    const analysis = []

    for (const branch of branches) {
      const branchRevenue = jsonDatabase.revenue.filter((r) => r.branch_id === branch.id)
      const branchEnrollments = jsonDatabase.enrollments.filter((e) => {
        const course = jsonDatabase.courses.find((c) => c.id === e.course_id)
        return course?.branch_id === branch.id
      })

      const totalRevenue = branchRevenue.reduce((sum, r) => sum + r.amount, 0)
      const commission = totalRevenue * branch.commission_rate
      const netRevenue = totalRevenue - commission

      analysis.push({
        branch,
        totalRevenue,
        commission,
        netRevenue,
        enrollmentCount: branchEnrollments.length,
      })
    }

    return analysis
  },
}

// Export for backward compatibility
export const mockDatabase = jsonDatabase
